RUN apt update -y && \
    apt install -y wget default-jdk maven && \
    wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.8/bin/apache-tomcat-9.0.8.tar.gz && \
    mkdir -p /opt/tomcat && \
    mv apache-tomcat-9.0.8.tar.gz /opt/tomcat && \
    cd /opt/tomcat && \
    tar -xvzf apache-tomcat-9.0.8.tar.gz && \
    groupadd tomcat && \
    useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat && \
    cd /opt/tomcat/apache-tomcat-9.0.8 && \
    chmod 777 conf bin && \
    chown -R tomcat webapps/ work/ temp/ logs/ bin/

